# Generated by Django 4.2.2 on 2023-07-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(max_length=200)),
                ('Sender', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
